export const partnerLogos = [
  "Aman Resorts",
  "Accor",
  "Hilton Hotels & Resorts",
  "IHG Hotels & Resorts",
  "Marriott International",
  "Hyatt",
  "Wyndham Hotels & Resorts",
  "Radisson Hotels",
  "Microsoft",
  "Fortinet",
  "Panduit",
  "VMware",
  "Cisco",
  "CommScope",
  "Dell",
  "Cisco Meraki",
  "Hanwha Vision",
  "Hewlett Packard Enterprise",
  "HPE Aruba Networking",
  "Alcatel-Lucent",
  "QSAN",
  "Ruckus",
  "Polycom",
  "Synology",
  "Juniper Networks",
  "XPossible",
  "IBM",
  "LG",
  "MCOMS",
  "Acer",
  "Sony",
  "Panasonic"
];

export const projectDetails = {
  "Euro Village Da Nang": { location: "Da Nang, Vietnam", scope: ["Smart Home", "ELV", "IT Design & Build"] },
  "Novotel Naman Village": { location: "Da Nang, Vietnam", scope: ["Admin Network", "Accor Standard", "Implementation"] },
  "Hilton Tapestry Casamia Hoian (2025)": { location: "Hoi An, Vietnam", scope: ["IT Appraisal", "ELV Appraisal", "Hilton Standard"] },
  "Hilton Tapestry Casamia Hoian (2026)": { location: "Hoi An, Vietnam", scope: ["Consulting", "Supervision", "IT & ELV"] },
  "Pullman Hai Phong": { location: "Hai Phong, Vietnam", scope: ["Admin Network", "Accor Standard", "Installation"] },
  "Hyatt Regency Da Nang": { location: "Da Nang, Vietnam", scope: ["Installation", "Maintenance", "IT Services"] },
  "Amanoi Resort": { location: "Khanh Hoa, Vietnam", scope: ["Network", "Wi-Fi", "VDI", "Office Workstation"] },
  "InterContinental Danang Sun Peninsula": { location: "Da Nang, Vietnam", scope: ["Wi-Fi", "CCTV", "Installation"] },
  "Hilton West Hanoi": { location: "Hanoi, Vietnam", scope: ["IT Design", "Consultancy"] },
  "Radisson Blu Resort Cam Ranh": { location: "Cam Ranh, Vietnam", scope: ["HSIA Gateway", "XPossible"] },
  "Radisson Hotel Da Nang": { location: "Da Nang, Vietnam", scope: ["IT Design & Build"] },
  "Wyndham Hoi An Royal Beachfront Resort & Villas": { location: "Hoi An, Vietnam", scope: ["IT Design & Build"] },
  "Golden Boutique Hotel Mang Den": { location: "Mang Den, Vietnam", scope: ["IT Design & Build", "RCU System"] },
  "Mercure Hai Phong": { location: "Hai Phong, Vietnam", scope: ["IT Design & Build"] },
  "Casino Hoiana": { location: "Quang Nam, Vietnam", scope: ["Surveillance", "Configuration", "Macau Casino Standard"] },
  "Hilton Da Nang": { location: "Da Nang, Vietnam", scope: ["IPTV System", "Installation"] },
  "JW Marriott Phu Quoc Emerald Bay Resort & Spa": { location: "Phu Quoc, Vietnam", scope: ["Wi-Fi", "IPTV", "Installation"] },
  "Hotel De La Coupole – MGallery Sapa": { location: "Sapa, Vietnam", scope: ["Design Consultancy", "Installation"] },
  "Pullman Da Nang Beach Resort": { location: "Da Nang, Vietnam", scope: ["Network Switch", "Server", "IT Equipment"] }
};

export const content = {
  vi: {
    locale: "vi",
    nav: [
      { href: "/", label: "Trang chủ" },
      { href: "/about", label: "Giới thiệu" },
      { href: "/solutions", label: "Giải pháp" },
      { href: "/services", label: "Dịch vụ" },
      { href: "/projects", label: "Dự án" },
      { href: "/contact", label: "Liên hệ" }
    ],
    heroBadge: "Đơn vị tư vấn, thiết kế và triển khai hệ thống công nghệ",
    heroTitle: "Giải pháp hệ thống CNTT, ELV và Network Intelligence cho Hospitality",
    heroDesc: "NetworkAI Technology Co., Ltd cung cấp dịch vụ tư vấn, thiết kế và triển khai hệ thống IT, ELV, Smart Home và Smart Building cho khách sạn, resort và doanh nghiệp, với đội ngũ có hơn 18 năm kinh nghiệm chuyên sâu.",
    heroPrimary: "Xem giải pháp",
    heroSecondary: "Liên hệ",
    homeMiniTitle: "Đội ngũ kỹ sư và chuyên gia IT với hơn 18 năm kinh nghiệm chuyên sâu trong Hospitality",
    homeMiniDesc: "NetworkAI Technology Co., Ltd được thành lập ngày 02/07/2024. Đội ngũ của công ty gồm các kỹ sư và chuyên gia IT có hơn 18 năm kinh nghiệm chuyên sâu trong tư vấn, thiết kế và triển khai hệ thống IT cho các dự án khách sạn và resort cao cấp.",
    aboutEyebrow: "Về NetworkAI",
    aboutTitle: "Đơn vị triển khai hệ thống CNTT và ELV cho Hospitality & Enterprise",
    aboutDesc: "NetworkAI Technology Co., Ltd được thành lập ngày 02/07/2024, quy tụ đội ngũ kỹ sư và chuyên gia IT giàu kinh nghiệm trong tư vấn, thiết kế và triển khai hệ thống cho các dự án khách sạn, resort và doanh nghiệp.",
    aboutExtra: "Chúng tôi cam kết hoàn thành dự án đúng tiến độ, đảm bảo chất lượng vượt mong đợi và luôn hỗ trợ khách hàng toàn diện trước, trong và sau quá trình triển khai dự án.",
    stats: [
      ["02/07/2024", "Ngày thành lập công ty"],
      ["18+", "Năm kinh nghiệm chuyên sâu của đội ngũ"],
      ["Hospitality", "Thế mạnh triển khai cho khách sạn và resort cao cấp"],
      ["Before • During • After", "Hỗ trợ khách hàng toàn diện trước, trong và sau dự án"]
    ],
    productEyebrow: "Sản phẩm nổi bật",
    productTitle: "NetOps Argus",
    productTag: "Nền tảng Network Intelligence On-Prem",
    productDesc: "NetOps Argus là nền tảng hỗ trợ giám sát và vận hành hạ tầng mạng tập trung, giúp đội ngũ kỹ thuật quan sát topology, theo dõi trạng thái thiết bị, quản lý inventory, điều tra syslog và rà soát thay đổi cấu hình trên cùng một bề mặt làm việc.",
    productPrimary: "Mở NetOps Argus",
    productSecondary: "Yêu cầu demo",
    productFeatures: [
      ["Topology trực quan", "Quan sát thiết bị, kết nối và phụ thuộc hệ thống để điều tra nhanh hơn."],
      ["Health Monitoring", "Theo dõi reachability, interface, uptime và tín hiệu suy giảm sớm."],
      ["Syslog có ngữ cảnh", "Đi từ cảnh báo đến bằng chứng vận hành ngay trong cùng workflow."],
      ["Config Review", "So sánh cấu hình, theo dõi drift và kiểm tra thay đổi rõ ràng."],
      ["Asset Inventory", "Quản lý model, serial, vai trò thiết bị và tình trạng tập trung."],
      ["SSH / Raw Access", "Đi sâu đến mức raw file và SSH khi cần xác minh kỹ thuật."]
    ],
    servicesEyebrow: "Dịch vụ",
    servicesTitle: "Giải pháp đồng bộ cho hạ tầng CNTT, ELV và công trình thông minh",
    servicesDesc: "NetworkAI cung cấp dịch vụ tư vấn, thiết kế, cung cấp thiết bị, lắp đặt, cấu hình, kiểm thử và hỗ trợ vận hành hệ thống cho các dự án hospitality và enterprise.",
    services: [
      ["Thiết kế hệ thống CNTT", "Thiết kế Network, WiFi, Server, Storage, Firewall, Security và hạ tầng phòng máy."],
      ["Triển khai hệ thống ELV", "CCTV, Access Control, PABX, PA, IPTV, hạ tầng cáp cấu trúc và các hệ thống kỹ thuật liên quan."],
      ["Smart Home / Smart Building", "Giải pháp điều khiển thông minh cho Lighting, Curtain, HVAC, Audio và các tiện ích tích hợp."],
      ["Tư vấn & thẩm định hệ thống", "Tư vấn kiến trúc giải pháp, rà soát thiết kế và tối ưu chi phí đầu tư."],
      ["Thi công & cấu hình", "Cung cấp thiết bị, triển khai lắp đặt, cấu hình hệ thống, test và bàn giao."],
      ["Bảo trì & hỗ trợ kỹ thuật", "Đồng hành cùng khách hàng trước, trong và sau triển khai, tối ưu và nâng cấp hệ thống lâu dài."]
    ],
    projectsEyebrow: "Dự án",
    projectsTitle: "Kinh nghiệm triển khai trên nhiều thương hiệu hospitality lớn",
    projectsDesc: "Danh mục dự án tiêu biểu thể hiện năng lực tư vấn, thiết kế và triển khai hệ thống IT, ELV và hạ tầng kỹ thuật cho các khách sạn, resort và công trình cao cấp.",
    projects: [
      ["Euro Village Da Nang", "SmartHome Design & Build; ELV & IT Design & Build"],
      ["Novotel Naman Village", "Providing & Installation Full Admin Network according to Accor standard"],
      ["Hilton Tapestry Casamia Hoian (2025)", "Appraisal of IT & ELV Infrastructure Design according to Hilton standard"],
      ["Hilton Tapestry Casamia Hoian (2026)", "IT & ELV system Consulting and Supervision"],
      ["Pullman Hai Phong", "Providing & Installation Full Admin Network according to Accor standard"],
      ["Hyatt Regency Da Nang", "Providing & Installation, Maintenance Services"],
      ["Amanoi Resort", "Providing & Installation Network, Wi-Fi system, Software License, VDI Solution, Office Workstation"],
      ["InterContinental Danang Sun Peninsula", "Providing & Installation Wi-Fi, CCTV System"],
      ["Hilton West Hanoi", "IT Design & Consultancy"],
      ["Radisson Blu Resort Cam Ranh", "HSIA Gateway Solution (Xpossible)"],
      ["Radisson Hotel Da Nang", "IT Design & Build"],
      ["Wyndham Hoi An Royal Beachfront Resort & Villas", "IT Design & Build"],
      ["Golden Boutique Hotel Mang Den", "IT Design & Build; RCU System Design & Build"],
      ["Mercure Hai Phong", "IT Design & Build"],
      ["Casino Hoiana", "Installation - Configuration Surveillance System under Macau Casino Standard"],
      ["Hilton Da Nang", "Providing & Installation IPTV System"],
      ["JW Marriott Phu Quoc Emerald Bay Resort & Spa", "Providing & Installation Wi-Fi System, IPTV System"],
      ["Hotel De La Coupole – MGallery Sapa", "Design Consultancy, Providing and Installation"],
      ["Pullman Da Nang Beach Resort", "Providing Network Switch, Server and IT equipment according to Accor standard"]
    ],
    contactEyebrow: "Liên hệ",
    contactTitle: "Trao đổi với chúng tôi về dự án của bạn",
    contactDesc: "Nếu bạn đang tìm kiếm một đối tác đáng tin cậy, đổi mới và tận tâm, hãy liên hệ với NetworkAI để cùng trao đổi về giải pháp phù hợp cho dự án của bạn.",
    address: "3rd floor, Kim Son Building - 18 Phan Thanh Tai, Hai Chau District, Da Nang City",
    consultationLabel: "Yêu cầu tư vấn",
    detailLabel: "Xem chi tiết",
    ctaStrip: "Đội ngũ NetworkAI luôn sẵn sàng đồng hành cùng khách hàng trong tư vấn, thiết kế, triển khai và hỗ trợ vận hành hệ thống.",
    footerTagline: "Amazing Solutions for Modern Infrastructure"
  },

  en: {
    locale: "en",
    nav: [
      { href: "/", label: "Home" },
      { href: "/about", label: "About" },
      { href: "/solutions", label: "Solutions" },
      { href: "/services", label: "Services" },
      { href: "/projects", label: "Projects" },
      { href: "/contact", label: "Contact" }
    ],
    heroBadge: "Technology consulting, design, and implementation company",
    heroTitle: "IT, ELV, and Network Intelligence Solutions for Hospitality",
    heroDesc: "NetworkAI Technology Co., Ltd delivers consulting, design, and implementation services for IT, ELV, Smart Home, and Smart Building systems for hotels, resorts, and enterprises, backed by a team with more than 18 years of specialized experience.",
    heroPrimary: "View Solutions",
    heroSecondary: "Contact",
    homeMiniTitle: "A team of engineers and IT specialists with more than 18 years of deep hospitality experience",
    homeMiniDesc: "NetworkAI Technology Co., Ltd was established on July 2, 2024. The company is built by a team of engineers and IT professionals with more than 18 years of specialized experience in consulting, designing, and deploying IT systems for high-end hotel and resort projects.",
    aboutEyebrow: "About NetworkAI",
    aboutTitle: "A technology and ELV implementation partner for Hospitality & Enterprise",
    aboutDesc: "NetworkAI Technology Co., Ltd was established on July 2, 2024, bringing together experienced engineers and IT experts in consulting, system design, and implementation for hotel, resort, and enterprise projects.",
    aboutExtra: "We are committed to completing projects on schedule, delivering quality beyond expectations, and supporting clients comprehensively before, during, and after project implementation.",
    stats: [
      ["02/07/2024", "Company establishment date"],
      ["18+", "Years of specialized team experience"],
      ["Hospitality", "Core strength in high-end hotel and resort projects"],
      ["Before • During • After", "Comprehensive support before, during, and after projects"]
    ],
    productEyebrow: "Featured Product",
    productTitle: "NetOps Argus",
    productTag: "On-Prem Network Intelligence Platform",
    productDesc: "NetOps Argus is a platform for centralized network operations and monitoring, enabling technical teams to visualize topology, track device health, manage inventory, investigate syslog, and review configuration changes within one operational workspace.",
    productPrimary: "Open NetOps Argus",
    productSecondary: "Request Demo",
    productFeatures: [
      ["Topology Visibility", "Visualize devices, connections, and dependencies for faster investigation."],
      ["Health Monitoring", "Track reachability, interface status, uptime, and early degradation signals."],
      ["Contextual Syslog", "Move from alert to operational evidence inside the same workflow."],
      ["Config Review", "Compare configurations, track drift, and validate changes clearly."],
      ["Asset Inventory", "Manage model, serial number, device role, and status in one place."],
      ["SSH / Raw Access", "Allow engineers to drill down to raw files and SSH when deep verification is required."]
    ],
    servicesEyebrow: "Services",
    servicesTitle: "Integrated solutions for IT infrastructure, ELV, and smart buildings",
    servicesDesc: "NetworkAI provides consulting, design, equipment supply, installation, configuration, testing, and operational support for hospitality and enterprise projects.",
    services: [
      ["IT System Design", "Design of Network, WiFi, Server, Storage, Firewall, Security, and server room infrastructure."],
      ["ELV System Deployment", "CCTV, Access Control, PABX, PA, IPTV, structured cabling, and related technical systems."],
      ["Smart Home / Smart Building", "Integrated control solutions for lighting, curtain, HVAC, audio, and smart utilities."],
      ["Consulting & System Review", "Solution architecture consulting, design review, and investment cost optimization."],
      ["Installation & Configuration", "Equipment supply, installation, configuration, system testing, and handover."],
      ["Maintenance & Technical Support", "Support clients before, during, and after deployment, with optimization and long-term upgrades."]
    ],
    projectsEyebrow: "Projects",
    projectsTitle: "Implementation experience across leading hospitality brands",
    projectsDesc: "Our featured portfolio demonstrates strong consulting, design, and implementation capability in IT systems, ELV, and technical infrastructure for hotels, resorts, and premium developments.",
    projects: [
      ["Euro Village Da Nang", "SmartHome Design & Build; ELV & IT Design & Build"],
      ["Novotel Naman Village", "Providing & Installation Full Admin Network according to Accor standard"],
      ["Hilton Tapestry Casamia Hoian (2025)", "Appraisal of IT & ELV Infrastructure Design according to Hilton standard"],
      ["Hilton Tapestry Casamia Hoian (2026)", "IT & ELV system Consulting and Supervision"],
      ["Pullman Hai Phong", "Providing & Installation Full Admin Network according to Accor standard"],
      ["Hyatt Regency Da Nang", "Providing & Installation, Maintenance Services"],
      ["Amanoi Resort", "Providing & Installation Network, Wi-Fi system, Software License, VDI Solution, Office Workstation"],
      ["InterContinental Danang Sun Peninsula", "Providing & Installation Wi-Fi, CCTV System"],
      ["Hilton West Hanoi", "IT Design & Consultancy"],
      ["Radisson Blu Resort Cam Ranh", "HSIA Gateway Solution (Xpossible)"],
      ["Radisson Hotel Da Nang", "IT Design & Build"],
      ["Wyndham Hoi An Royal Beachfront Resort & Villas", "IT Design & Build"],
      ["Golden Boutique Hotel Mang Den", "IT Design & Build; RCU System Design & Build"],
      ["Mercure Hai Phong", "IT Design & Build"],
      ["Casino Hoiana", "Installation - Configuration Surveillance System under Macau Casino Standard"],
      ["Hilton Da Nang", "Providing & Installation IPTV System"],
      ["JW Marriott Phu Quoc Emerald Bay Resort & Spa", "Providing & Installation Wi-Fi System, IPTV System"],
      ["Hotel De La Coupole – MGallery Sapa", "Design Consultancy, Providing and Installation"],
      ["Pullman Da Nang Beach Resort", "Providing Network Switch, Server and IT equipment according to Accor standard"]
    ],
    contactEyebrow: "Contact",
    contactTitle: "Talk to us about your project",
    contactDesc: "If you are looking for a reliable, innovative, and dedicated partner, contact NetworkAI to discuss the right solution for your project.",
    address: "3rd floor, Kim Son Building - 18 Phan Thanh Tai, Hai Chau District, Da Nang City",
    consultationLabel: "Request Consultation",
    detailLabel: "View Details",
    ctaStrip: "The NetworkAI team is always ready to support clients in consulting, design, implementation, and operational assistance.",
    footerTagline: "Amazing Solutions for Modern Infrastructure"
  }
};

export function getContent(searchParams) {
  const lang = searchParams && searchParams.lang === "en" ? "en" : "vi";
  return content[lang];
}
